# Generated by Django 5.2.1 on 2025-09-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_normaluserprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normaluserprofile',
            old_name='form_link',
            new_name='form_link1',
        ),
        migrations.AddField(
            model_name='normaluserprofile',
            name='form_link2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='normaluserprofile',
            name='form_link3',
            field=models.URLField(blank=True, null=True),
        ),
    ]
