# secrets.toml

OPENAI_API_KEY = "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"
